# Generated by Django 4.2.20 on 2025-06-11 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5941e135-af71-48dc-a776-08fa388fd9bd"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
