# Generated by Django 4.2.23 on 2025-06-26 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hash_part',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid_part',
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac3e47ed-0b6f-4cd9-868c-b50f066e9379'), primary_key=True, serialize=False, unique=True),
        ),
    ]
