# Generated by Django 4.2.23 on 2025-06-28 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_created_at_remove_user_hash_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d6feb75e-fe5b-4b86-8f68-ea82b96c993d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
