# Generated by Django 4.2.23 on 2025-07-10 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_fullname_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('28b85657-3891-4f2d-95d4-b0a1b9e9609d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
