# Generated by Django 4.2.23 on 2025-07-10 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b962d892-f3dc-4db6-b055-7bbfca9115c8'), primary_key=True, serialize=False, unique=True),
        ),
    ]
