# Generated by Django 4.2.23 on 2025-07-11 05:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9115a72f-ac03-4f12-b0d7-3e330e0edd33'), primary_key=True, serialize=False, unique=True),
        ),
    ]
