# Generated by Django 4.2.23 on 2025-07-13 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0fe52917-6f23-41d1-b1b7-5f21dd2830e2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
