# Generated by Django 4.2.23 on 2025-07-11 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('action_type', models.CharField(max_length=100)),
                ('request_path', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('device_info', models.JSONField()),
                ('location_info', models.JSONField(null=True)),
                ('parameters', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('alert_type', models.CharField(choices=[('BRUTE_FORCE', 'تلاش برای حمله Brute Force'), ('UNUSUAL_LOCATION', 'دسترسی از مکان غیرعادی'), ('ACCOUNT_TAKEOVER', 'تلاش برای تصاحب حساب'), ('SUSPICIOUS_ACTIVITY', 'فعالیت مشکوک')], max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('details', models.JSONField()),
                ('related_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='security_app.useractivitylog')),
            ],
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'timestamp'], name='security_ap_user_id_7b49f5_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='security_ap_ip_addr_a090f5_idx'),
        ),
    ]
